"""Remove Caregiver from models

Revision ID: 261167dd2c6c
Revises: b0c9f7ed8e68
Create Date: 2026-07-09 19:33:07.271596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261167dd2c6c'
down_revision: Union[str, Sequence[str], None] = 'b0c9f7ed8e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caregivers_id'), table_name='caregivers')
    op.drop_table('caregivers')
    with op.batch_alter_table('patients') as batch_op:
        batch_op.drop_column('caregiver_id')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ADMIN', 'DOCTOR', 'PATIENT', name='roleenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'DOCTOR', 'PATIENT', name='roleenum'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
    op.add_column('patients', sa.Column('caregiver_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'patients', 'caregivers', ['caregiver_id'], ['id'])
    op.create_table('caregivers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('relationship_to_patient', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_caregivers_id'), 'caregivers', ['id'], unique=False)
    # ### end Alembic commands ###
