"""add auto_refill, availability_status, ai_recommendation applied, audit_logs table

Revision ID: d2b91b682a9d
Revises: 261167dd2c6c
Create Date: 2026-07-10 00:34:46.323224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b91b682a9d'
down_revision: Union[str, Sequence[str], None] = '261167dd2c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    NOTE: autogenerate also detected a `caregivers` table / `patients.caregiver_id`
    column drop. That's pre-existing drift — the DB is stamped at 261167dd2c6c (which
    should have already dropped those) but its actual schema never caught up, likely
    because the dev DB was seeded via create_all rather than `alembic upgrade`. That
    drift is unrelated to this change and is intentionally left out of this migration;
    it should be resolved on its own (re-run 261167dd2c6c's DDL directly, or a follow-up
    migration) rather than bundled into an unrelated feature migration.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'DANGER', name='auditseverity'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.add_column('ai_recommendations', sa.Column('applied', sa.Boolean(), nullable=True))
    op.add_column('doctors', sa.Column('availability_status', sa.String(), nullable=True))
    op.add_column('medicines', sa.Column('auto_refill', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'auto_refill')
    op.drop_column('doctors', 'availability_status')
    op.drop_column('ai_recommendations', 'applied')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
