/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVoiceRouteImport } from './routes/_app.voice'
import { Route as AppSmartBottleRouteImport } from './routes/_app.smart-bottle'
import { Route as AppMedicationRouteImport } from './routes/_app.medication'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppSmartBottleRoute = AppSmartBottleRouteImport.update({
  id: '/smart-bottle',
  path: '/smart-bottle',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicationRoute = AppMedicationRouteImport.update({
  id: '/medication',
  path: '/medication',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/medication': typeof AppMedicationRoute
  '/smart-bottle': typeof AppSmartBottleRoute
  '/voice': typeof AppVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/medication': typeof AppMedicationRoute
  '/smart-bottle': typeof AppSmartBottleRoute
  '/voice': typeof AppVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/medication': typeof AppMedicationRoute
  '/_app/smart-bottle': typeof AppSmartBottleRoute
  '/_app/voice': typeof AppVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/medication' | '/smart-bottle' | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/medication' | '/smart-bottle' | '/voice'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/medication'
    | '/_app/smart-bottle'
    | '/_app/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/voice': {
      id: '/_app/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/smart-bottle': {
      id: '/_app/smart-bottle'
      path: '/smart-bottle'
      fullPath: '/smart-bottle'
      preLoaderRoute: typeof AppSmartBottleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medication': {
      id: '/_app/medication'
      path: '/medication'
      fullPath: '/medication'
      preLoaderRoute: typeof AppMedicationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMedicationRoute: typeof AppMedicationRoute
  AppSmartBottleRoute: typeof AppSmartBottleRoute
  AppVoiceRoute: typeof AppVoiceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMedicationRoute: AppMedicationRoute,
  AppSmartBottleRoute: AppSmartBottleRoute,
  AppVoiceRoute: AppVoiceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
