/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTelemedicineRouteImport } from './routes/_app.telemedicine'
import { Route as AppSmartBottleRouteImport } from './routes/_app.smart-bottle'
import { Route as AppScannerRouteImport } from './routes/_app.scanner'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRefillRouteImport } from './routes/_app.refill'
import { Route as AppPrescriptionsRouteImport } from './routes/_app.prescriptions'
import { Route as AppPatientsRouteImport } from './routes/_app.patients'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMedicationCalendarRouteImport } from './routes/_app.medication-calendar'
import { Route as AppMedicationRouteImport } from './routes/_app.medication'
import { Route as AppDoctorsRouteImport } from './routes/_app.doctors'
import { Route as AppDevicesRouteImport } from './routes/_app.devices'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'
import { Route as AppAiAssistantRouteImport } from './routes/_app.ai-assistant'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTelemedicineRoute = AppTelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => AppRoute,
} as any)
const AppSmartBottleRoute = AppSmartBottleRouteImport.update({
  id: '/smart-bottle',
  path: '/smart-bottle',
  getParentRoute: () => AppRoute,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRefillRoute = AppRefillRouteImport.update({
  id: '/refill',
  path: '/refill',
  getParentRoute: () => AppRoute,
} as any)
const AppPrescriptionsRoute = AppPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicationCalendarRoute = AppMedicationCalendarRouteImport.update({
  id: '/medication-calendar',
  path: '/medication-calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicationRoute = AppMedicationRouteImport.update({
  id: '/medication',
  path: '/medication',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorsRoute = AppDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/appointments': typeof AppAppointmentsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/doctors': typeof AppDoctorsRoute
  '/medication': typeof AppMedicationRoute
  '/medication-calendar': typeof AppMedicationCalendarRoute
  '/notifications': typeof AppNotificationsRoute
  '/patients': typeof AppPatientsRoute
  '/prescriptions': typeof AppPrescriptionsRoute
  '/refill': typeof AppRefillRoute
  '/reports': typeof AppReportsRoute
  '/scanner': typeof AppScannerRoute
  '/smart-bottle': typeof AppSmartBottleRoute
  '/telemedicine': typeof AppTelemedicineRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/appointments': typeof AppAppointmentsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/devices': typeof AppDevicesRoute
  '/doctors': typeof AppDoctorsRoute
  '/medication': typeof AppMedicationRoute
  '/medication-calendar': typeof AppMedicationCalendarRoute
  '/notifications': typeof AppNotificationsRoute
  '/patients': typeof AppPatientsRoute
  '/prescriptions': typeof AppPrescriptionsRoute
  '/refill': typeof AppRefillRoute
  '/reports': typeof AppReportsRoute
  '/scanner': typeof AppScannerRoute
  '/smart-bottle': typeof AppSmartBottleRoute
  '/telemedicine': typeof AppTelemedicineRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/devices': typeof AppDevicesRoute
  '/_app/doctors': typeof AppDoctorsRoute
  '/_app/medication': typeof AppMedicationRoute
  '/_app/medication-calendar': typeof AppMedicationCalendarRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/patients': typeof AppPatientsRoute
  '/_app/prescriptions': typeof AppPrescriptionsRoute
  '/_app/refill': typeof AppRefillRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/scanner': typeof AppScannerRoute
  '/_app/smart-bottle': typeof AppSmartBottleRoute
  '/_app/telemedicine': typeof AppTelemedicineRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/appointments'
    | '/audit-logs'
    | '/dashboard'
    | '/devices'
    | '/doctors'
    | '/medication'
    | '/medication-calendar'
    | '/notifications'
    | '/patients'
    | '/prescriptions'
    | '/refill'
    | '/reports'
    | '/scanner'
    | '/smart-bottle'
    | '/telemedicine'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/appointments'
    | '/audit-logs'
    | '/dashboard'
    | '/devices'
    | '/doctors'
    | '/medication'
    | '/medication-calendar'
    | '/notifications'
    | '/patients'
    | '/prescriptions'
    | '/refill'
    | '/reports'
    | '/scanner'
    | '/smart-bottle'
    | '/telemedicine'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/ai-assistant'
    | '/_app/appointments'
    | '/_app/audit-logs'
    | '/_app/dashboard'
    | '/_app/devices'
    | '/_app/doctors'
    | '/_app/medication'
    | '/_app/medication-calendar'
    | '/_app/notifications'
    | '/_app/patients'
    | '/_app/prescriptions'
    | '/_app/refill'
    | '/_app/reports'
    | '/_app/scanner'
    | '/_app/smart-bottle'
    | '/_app/telemedicine'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/telemedicine': {
      id: '/_app/telemedicine'
      path: '/telemedicine'
      fullPath: '/telemedicine'
      preLoaderRoute: typeof AppTelemedicineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/smart-bottle': {
      id: '/_app/smart-bottle'
      path: '/smart-bottle'
      fullPath: '/smart-bottle'
      preLoaderRoute: typeof AppSmartBottleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scanner': {
      id: '/_app/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/refill': {
      id: '/_app/refill'
      path: '/refill'
      fullPath: '/refill'
      preLoaderRoute: typeof AppRefillRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prescriptions': {
      id: '/_app/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof AppPrescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients': {
      id: '/_app/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medication-calendar': {
      id: '/_app/medication-calendar'
      path: '/medication-calendar'
      fullPath: '/medication-calendar'
      preLoaderRoute: typeof AppMedicationCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medication': {
      id: '/_app/medication'
      path: '/medication'
      fullPath: '/medication'
      preLoaderRoute: typeof AppMedicationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctors': {
      id: '/_app/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AppDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppDoctorsRoute: typeof AppDoctorsRoute
  AppMedicationRoute: typeof AppMedicationRoute
  AppMedicationCalendarRoute: typeof AppMedicationCalendarRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPrescriptionsRoute: typeof AppPrescriptionsRoute
  AppRefillRoute: typeof AppRefillRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScannerRoute: typeof AppScannerRoute
  AppSmartBottleRoute: typeof AppSmartBottleRoute
  AppTelemedicineRoute: typeof AppTelemedicineRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppDoctorsRoute: AppDoctorsRoute,
  AppMedicationRoute: AppMedicationRoute,
  AppMedicationCalendarRoute: AppMedicationCalendarRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPrescriptionsRoute: AppPrescriptionsRoute,
  AppRefillRoute: AppRefillRoute,
  AppReportsRoute: AppReportsRoute,
  AppScannerRoute: AppScannerRoute,
  AppSmartBottleRoute: AppSmartBottleRoute,
  AppTelemedicineRoute: AppTelemedicineRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
